name: logan_misses_you
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.12
  image_picker: ^0.6.6+1
  matrix_gesture_detector: ^0.1.0
  permission_handler: ^5.0.0+hotfix.5
  image_gallery_saver: ^1.2.2
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2
  stacked: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/base.png
    - assets/images/image-placeholder.png
  