name: logan_misses_you
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.12
  image_picker: ^0.6.6+1
  matrix_gesture_detector: ^0.1.0
  permission_handler: ^5.0.0+hotfix.5
  image_gallery_saver: ^1.2.2
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2

  # State Management
  stacked: ^1.2.2

  # Navigation
  auto_route: ^0.5.0
  stacked_services: ^0.3.0+1

  # Inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/base.png
    - assets/images/image-placeholder.png
